#!/usr/bin/env python3
"""Phase 18 plan 02 coverage: capabilities.json, the agent-facing
capability disclosure manifest (18-CONTEXT D-03), is generated by
tools/capabilities_manifest.py, byte-stable, checked in fresh, and
contains no network code.

The checked-in manifest must be byte-identical to a fresh regeneration,
so a command, route, or skill added without rerunning the generator
fails here instead of shipping a stale disclosure. The generator must
stay static and local: the existing disclosure-gated updater is the only
network path that ever fetches a newer manifest, so no http, urllib, or
socket import may appear in the generator at all.

Standard library only, runnable as `python tests/capabilities_roundtrip.py`.
"""
import json
import os
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GENERATOR = os.path.join(ROOT, "tools", "capabilities_manifest.py")
MANIFEST = os.path.join(ROOT, "capabilities.json")


def fail(msg):
    print("FAIL: " + msg)
    sys.exit(1)


def test_regeneration_is_byte_identical():
    tmpdir = tempfile.mkdtemp()
    out = os.path.join(tmpdir, "capabilities.json")
    proc = subprocess.run([sys.executable, GENERATOR, out],
                          capture_output=True, text=True, cwd=ROOT)
    if proc.returncode != 0:
        fail("generator exited %d: %s%s"
             % (proc.returncode, proc.stdout, proc.stderr))
    fresh = open(out, "rb").read()
    checked_in = open(MANIFEST, "rb").read()
    if fresh != checked_in:
        fail("capabilities.json is stale; run "
             "python tools/capabilities_manifest.py and commit the result")


def test_generator_has_no_network_imports():
    source = open(GENERATOR, encoding="utf-8").read()
    for module in ("http", "urllib", "socket"):
        for form in ("import %s" % module, "from %s" % module):
            if form in source:
                fail("tools/capabilities_manifest.py contains %r; the "
                     "manifest is static and local, and the generator "
                     "must never open a network path" % form)


def test_manifest_shape():
    doc = json.load(open(MANIFEST, encoding="utf-8"))
    if doc.get("schema_version") != 1:
        fail("schema_version is %r, expected 1" % doc.get("schema_version"))
    commands = doc.get("commands")
    if not commands:
        fail("manifest has no commands")
    for entry in commands:
        if not entry.get("since"):
            fail("command %r has an empty since version"
                 % entry.get("name"))


def main():
    test_regeneration_is_byte_identical()
    test_generator_has_no_network_imports()
    test_manifest_shape()
    print("ok: capabilities roundtrip")
    return 0


if __name__ == "__main__":
    sys.exit(main())
