import { pathToFileURL, fileURLToPath } from 'node:url';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const { chromium } = await import(process.env.ITEMBANK_PLAYWRIGHT_MODULE || 'playwright');
const root=fileURLToPath(new URL('.', import.meta.url));
const browser=await chromium.launch({executablePath:process.env.ITEMBANK_CHROMIUM,headless:true});
const errors=[];
try {
const page=await browser.newPage({viewport:{width:390,height:844}});
page.on('pageerror',e=>errors.push(e.message));
page.on('request',r=>{if(/^https?:/.test(r.url()))errors.push(r.url())});
await page.goto(pathToFileURL(`${root}/figures.html`).href);
assert(await page.locator('[name="format"][value="placement"]').isChecked());
assert(await page.locator('#show-bank').isChecked());
assert(await page.locator('#show-bank').isDisabled());
await page.locator('[name="format"][value="blank"]').check();
await page.locator('#instruction').fill('Name each marked process.');
await page.locator('#purpose').fill('My retained author note');
await page.locator('[data-select="condensation"]').focus();
await page.keyboard.press('Enter');
assert.equal(await page.locator('[data-select="condensation"]').getAttribute('aria-pressed'),'true');
await page.locator('#preview-view').click();
assert.equal(await page.locator('#preview-instruction').textContent(),'Name each marked process.');
assert.equal(await page.locator('#response-area input').count(),3);
assert(!(await page.locator('#visual').textContent()).includes('Evaporation'));
assert(!(await page.locator('#visual').textContent()).includes('Condensation'));
await page.locator('[data-answer="evaporation"]').fill('My trial response');
assert.deepEqual(await page.locator('#answer-bank li').allTextContents(),['Condensation','Evaporation','Precipitation','Runoff']);
await page.locator('#show-bank').uncheck();
assert.equal(await page.locator('#answer-bank').count(),0);
assert.equal(await page.locator('[data-answer="evaporation"]').inputValue(),'My trial response');
await page.locator('#source-open').click();
assert(await page.locator('#source-dialog').evaluate(e=>e.open));
assert.match(await page.locator('#source-content').textContent(),/Evaporation/);
assert.equal(await page.locator('#dialog-locator').textContent(),'figures.md#source-figure-2');
await page.keyboard.press('Escape');
assert.equal(await page.evaluate(()=>document.activeElement.id),'source-open');
assert.equal(await page.locator('[data-answer="evaporation"]').inputValue(),'My trial response');
await page.locator('#edit-view').click();
await page.locator('[name="format"][value="placement"]').check();
assert(await page.locator('#show-bank').isChecked());
assert(await page.locator('#show-bank').isDisabled());
await page.locator('#preview-view').click();
await page.locator('[data-label="evaporation"]').focus();
await page.keyboard.press('Enter');
await page.locator('[data-target="condensation"]').focus();
await page.keyboard.press('Enter');
assert.equal(await page.locator('[data-target="condensation"]').textContent(),'Evaporation');
await page.locator('[data-answer="precipitation"]').selectOption('Runoff');
assert.equal(await page.locator('[data-target="precipitation"]').textContent(),'Runoff');
assert.match(await page.locator('#activity-status').textContent(),/Nothing is evaluated/);
await page.setViewportSize({width:1280,height:900});
await page.locator('[data-label="runoff"]').dragTo(page.locator('[data-target="evaporation"]'));
assert.equal(await page.locator('[data-target="evaporation"]').textContent(),'Runoff');
assert.equal(await page.locator('[data-answer="precipitation"]').inputValue(),'');
assert.equal(await page.locator('[data-target="precipitation"]').textContent(),'3');
assert.match(await page.locator('[data-target="evaporation"]').getAttribute('aria-label'),/placed Runoff/);
await page.locator('[name="format"][value="blank"]').check();
assert(!(await page.locator('#show-bank').isChecked()));
assert.equal(await page.locator('#answer-bank').count(),0);
assert.equal(await page.locator('[data-answer="evaporation"]').inputValue(),'My trial response');
await page.setViewportSize({width:390,height:844});
await page.locator('#review-open').click();
assert.match(await page.locator('#draft-text').textContent(),/My retained author note/);
assert.match(await page.locator('#draft-text').textContent(),/Name each marked process/);
assert.match(await page.locator('#draft-text').textContent(),/Answer bank: hidden for recall practice/);
await page.keyboard.press('Escape');
await page.locator('[data-source="table"]').click();
assert(await page.locator('#show-bank').isChecked());
assert.equal(await page.locator('#visual table.rain tbody tr').count(),4);
await page.locator('[data-select="1-1"]').click();
await page.locator('#instruction').fill('Fill the selected measurements.');
await page.locator('#preview-view').click();
assert.equal(await page.locator('#visual input').count(),2);
assert.equal(await page.locator('#visual input[aria-label="Monday, Gauge B in millimeters"]').count(),1);
await page.locator('[data-answer="0-2"]').fill('17');
assert.deepEqual(await page.locator('#answer-bank li').allTextContents(),['0 mm','4 mm','5 mm','7 mm','9 mm','12 mm','18 mm']);
await page.locator('#show-bank').uncheck();
assert.equal(await page.locator('[data-answer="0-2"]').inputValue(),'17');
await page.locator('#source-open').click();
assert.match(await page.locator('#source-content').textContent(),/18 mm/);
assert.equal(await page.locator('#dialog-locator').textContent(),'figures.md#source-table-1');
await page.keyboard.press('Escape');
assert.equal(await page.locator('[data-answer="0-2"]').inputValue(),'17');
await page.locator('[data-source="figure"]').click();
assert.equal(await page.locator('#instruction').inputValue(),'Name each marked process.');
assert.equal(await page.locator('#purpose').inputValue(),'My retained author note');
assert(!(await page.locator('#show-bank').isChecked()));
await page.locator('#reset').click();
assert.match(await page.locator('#activity-status').textContent(),/Studio reset/);
assert.equal(await page.locator('#selection-count').textContent(),'2 labels selected');
assert(await page.locator('[name="format"][value="placement"]').isChecked());
assert(await page.locator('#show-bank').isChecked());
for(const id of ['evaporation','precipitation'])await page.locator(`[data-select="${id}"]`).click();
assert(await page.locator('#preview-view').isDisabled());
assert(await page.locator('#review-open').isDisabled());
console.log('PASS figures: drag default, optional typed banks, one-use label movement, keyboard and drag placement, source return, retained drafts, review and reset');
await page.goto(pathToFileURL(`${root}/chapters.html`).href);
const original=await page.locator('[data-chapter]').evaluateAll(es=>es.map(e=>e.dataset.chapter).sort());
await page.locator('[data-axis="depth"]').click();
assert.equal(await page.locator('#tier-title').textContent(),'Prerequisite depth');
const depthGroups=await page.locator('#groups .group').evaluateAll(groups=>groups.map(g=>[...g.querySelectorAll('[data-chapter]')].map(b=>b.dataset.chapter)));
assert.deepEqual(depthGroups,[['CH-WC-01','CH-RF-02'],['CH-WS-03'],['CH-ST-04']]);
assert.match(await page.locator('#chapter-meta').textContent(),/CH-RF-02/);
assert.deepEqual(await page.locator('[data-chapter]').evaluateAll(es=>es.map(e=>e.dataset.chapter).sort()),original);
for(const chapter of original) assert(await page.locator(`[data-chapter="${chapter}"]`).isVisible());
await page.locator('[data-chapter="CH-ST-04"]').focus();
await page.keyboard.press('Enter');
assert.match(await page.locator('#chapter-meta').textContent(),/CH-ST-04.*OBJ-ST-04/);
assert.equal(await page.evaluate(()=>document.activeElement.id),'reader');
assert.equal(await page.locator('#prereq-list button').count(),2);
await page.locator('#inspect-source').click();
assert(await page.locator('#source-dialog').evaluate(e=>e.open));
assert.equal(await page.locator('#dialog-locator').textContent(),'chapters.md#ch-st-04');
await page.keyboard.press('Escape');
assert.equal(await page.evaluate(()=>document.activeElement.id),'inspect-source');
assert.equal(await page.locator('#tier-title').textContent(),'Prerequisite depth');
await page.locator('#prereq-list button').first().click();
assert.match(await page.locator('#chapter-meta').textContent(),/CH-RF-02/);
await page.locator('[data-chapter="CH-ST-04"]').click();
await page.locator('#reset').click();
assert.match(await page.locator('#chapter-meta').textContent(),/CH-ST-04/);
await page.locator('#next').click();
assert.match(await page.locator('#chapter-meta').textContent(),/CH-WC-01/);
await page.locator('#previous').click();
assert.match(await page.locator('#chapter-meta').textContent(),/CH-ST-04/);
console.log('PASS chapters: derived depth groups, prerequisite navigation, source dialog return, stable IDs, narrow-screen reachability, reset, previous/next');
for(const name of ['figures','chapters']){
 await page.goto(pathToFileURL(`${root}/${name}.html`).href);
 if(name==='figures')await page.locator('#source-open').click();
 const links=await page.locator('a[href*=".md#"]').evaluateAll(es=>es.map(e=>e.getAttribute('href')));
 assert(links.length,`${name}: exact source link missing`);
 for(const href of links){const [file,anchor]=href.split('#');const source=await readFile(`${root}/${file}`,'utf8');assert(source.includes(`id="${anchor}"`),href)}
 assert.equal(await page.evaluate(()=>localStorage.length),0);
 assert.equal(await page.evaluate(()=>sessionStorage.length),0);
}
assert.deepEqual(errors,[]);
console.log('PASS exact Markdown source anchors, no browser storage, no network or script errors');
await page.goto(pathToFileURL(`${root}/figures.html`).href);
await page.locator('#preview-view').click();
for(const width of [1440,390]){
 await page.setViewportSize({width,height:1000});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`figure overflow at ${width}`);
 if(process.env.ITEMBANK_SCREENSHOT_DIR)await page.screenshot({path:`${process.env.ITEMBANK_SCREENSHOT_DIR}/figure-bank-${width}.png`,fullPage:true});
}
console.log('PASS updated figure preview at desktop and narrow widths');
}finally{await browser.close()}
