import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {chromium} from '/tmp/itembank-overhaul-qa/node_modules/playwright/index.mjs';
const root=path.dirname(fileURLToPath(import.meta.url));
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://local');let file;if(url.pathname.startsWith('/assets/fonts/'))file=path.resolve(root,'../../../fonts',url.pathname.slice(14));else if(url.pathname==='/baseline-original.html')file=path.resolve(root,'../../ui-overhaul-20260930/visual/workshop-light.html');else file=path.join(root,url.pathname==='/'?'index.html':url.pathname);const ext=path.extname(file);res.setHeader('Content-Type',({'.css':'text/css','.js':'text/javascript','.html':'text/html','.woff2':'font/woff2'})[ext]||'text/plain');res.end(await readFile(file));}catch{res.writeHead(404);res.end('Not found');}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const origin=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const metrics=[];await mkdir(path.join(root,'observed'),{recursive:true});
try{
for(const composition of ['atlas','studio','baseline'])for(const theme of ['light','dark'])for(const width of [1440,390]){
 const page=await browser.newPage({viewport:{width,height:1000},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`${origin}/?composition=${composition}&theme=${theme}`);await page.evaluate(()=>document.fonts.ready);await page.locator('#elapsed').fill('8');assert.equal(await page.locator('#a-value').textContent(),'24 m');assert.equal(await page.locator('#b-value').textContent(),'40 m');await page.locator('[data-time="6"]').click();assert.equal(await page.locator('#clock').textContent(),'6');
 const observation=await page.evaluate(()=>({width:innerWidth,overflow:document.documentElement.scrollWidth-innerWidth,scheme:getComputedStyle(document.documentElement).colorScheme,fontLoaded:document.fonts.check('18px "Source Serif 4"'),targets:[...document.querySelectorAll('button,select,nav a,summary,input[type=range],fieldset label')].filter(x=>x.getBoundingClientRect().width).map(x=>({name:x.textContent.trim().slice(0,40),height:x.getBoundingClientRect().height})),motion:getComputedStyle(document.querySelector('.walker')).transitionDuration}));
 assert.equal(observation.overflow,0);assert(observation.targets.every(x=>x.height>=44));assert.equal(observation.motion,'0s');assert.equal(errors.length,0);
 await page.evaluate(()=>{document.activeElement.blur();scrollTo(0,0)});await page.screenshot({path:path.join(root,'observed',`${composition}-${theme}-${width}.png`),fullPage:true});
 await page.locator('.note-more').evaluate(x=>x.open=true);await page.locator('#private-note').fill('Keep the 3:5 ratio.');await page.locator('input[value=double]').check();await page.locator('#reveal').click();assert.equal(await page.locator('#clock').textContent(),'12');assert.match(await page.locator('#feedback').textContent(),/unscored/);await page.locator('button[data-practice]').click();await page.locator('#practice-draft').fill('3 times 8 = 24');await page.getByRole('button',{name:'Return to the lesson',exact:true}).click();assert.equal(await page.locator('#private-note').inputValue(),'Keep the 3:5 ratio.');assert.equal(await page.locator('#practice-draft').inputValue(),'3 times 8 = 24');
 await page.locator('#composition').selectOption(composition==='atlas'?'studio':'atlas');assert.equal(await page.locator('#private-note').inputValue(),'Keep the 3:5 ratio.');metrics.push({composition,theme,...observation,detourDraftsRetained:true});await page.close();}
for(const mode of ['light','dark'])for(const width of [1440,390]){const p=await browser.newPage({viewport:{width,height:1000}});await p.goto(`${origin}/source-baseline-${mode}.html`);await p.evaluate(()=>document.fonts.ready);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0);await p.screenshot({path:path.join(root,'observed',`source-baseline-${mode}-${width}.png`),fullPage:true});await p.close();}
const original=await browser.newPage({viewport:{width:1440,height:1000}});await original.goto(`${origin}/baseline-original.html`);await original.evaluate(()=>document.fonts.ready);await original.screenshot({path:path.join(root,'observed','current-original-1440.png'),fullPage:true});await original.close();
const live=await browser.newPage({viewport:{width:1440,height:1000}});await live.goto(`${origin}/?composition=studio`);await live.locator('#elapsed').fill('12');await live.waitForTimeout(180);assert.equal(await live.locator('#a-value').textContent(),'36 m');assert.equal(await live.locator('#b-value').textContent(),'60 m');await live.screenshot({path:path.join(root,'observed','studio-time12-1440.png'),fullPage:true});await live.locator('button[data-practice]').click();await live.screenshot({path:path.join(root,'observed','studio-practice-1440.png')});await live.close();
const nojs=await browser.newPage({viewport:{width:390,height:1000},javaScriptEnabled:false});await nojs.goto(origin);assert(await nojs.locator('noscript').isVisible());assert(await nojs.locator('blockquote').isVisible());await nojs.screenshot({path:path.join(root,'observed','atlas-no-script-390.png'),fullPage:true});await nojs.close();
const keyboard=await browser.newPage({viewport:{width:390,height:1000}});await keyboard.goto(origin);await keyboard.locator('#elapsed').focus();await keyboard.keyboard.press('ArrowRight');assert.equal(await keyboard.locator('#clock').textContent(),'7');assert.equal(await keyboard.locator('#elapsed').evaluate(x=>getComputedStyle(x).outlineStyle),'solid');await keyboard.close();
await writeFile(path.join(root,'observed','metrics.json'),JSON.stringify(metrics,null,2));console.log('PASS 12 full-page renders; no overflow; 44px targets; diagram values; drafts retained through detour and composition switch; keyboard range; reduced motion; no-script meaning.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
