/* Presentation-only responses. Never executes, evaluates, or grades code. */
const exampleState = {kind:'code', values:{}, traced:false, order:['print(total)','    total += value','total = 0','for value in [2, 4, 6]:'], points:[], preview:false};
const escapeText = value => String(value ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const exampleKinds = [['code','Code workspace','Predict, trace, and draft a repair'],['order','Arrange code','Build an ordered program'],['table','Complete a table','Reason across related values'],['visual','Select on a visual','Connect a diagram to a response'],['written','Explain an argument','Keep evidence beside your writing']];
function exampleField(key,label,area=false,initial=''){
 const value=exampleState.values[key]??initial;
 return `<label class="response-field">${label}${area?`<textarea data-response="${key}" rows="4" spellcheck="false">${escapeText(value)}</textarea>`:`<input data-response="${key}" type="text" value="${escapeText(value)}" autocomplete="off" ${key==='prediction'&&exampleState.traced?'readonly':''}>`}</label>`;
}
function codeExample(){return `<div class="task-split"><section><div class="code-head"><span>PYTHON 3 · READ ONLY</span><span>4 lines</span></div><pre class="source-code" tabindex="0" aria-label="Python source code"><code><span class="code-line"><span class="syntax-name">total</span> = <span class="syntax-number">0</span></span>
<span class="code-line"><span class="syntax-keyword">for</span> value <span class="syntax-keyword">in</span> [<span class="syntax-number">2, 4, 6</span>]:</span>
<span class="code-line">    total += value</span>
<span class="code-line"><span class="syntax-name">print</span>(total)</span></code></pre><p class="micro">Indentation and line breaks are part of the question. Line numbers are visual guides.</p><details><summary>Draft a small code change</summary><p>Change the program to add only values greater than 2. This is an editing surface, not a code runner.</p>${exampleField('repair','Your Python draft',true,'total = 0\nfor value in [2, 4, 6]:\n    total += value\nprint(total)')}<span class="pill">Execution unavailable in this showcase</span></details></section><section><p class="eyebrow">PREDICT FIRST</p><h2>What will this program print?</h2>${exampleField('prediction','Your predicted output')}<p class="micro">Keep an initial prediction before unpacking the loop.</p>${exampleState.traced?`<p class="pill">Initial prediction: ${escapeText(exampleState.values.initialPrediction)}</p><h3 style="margin-top:20px">Build your own trace</h3><p class="micro">Fill in the state after each pass. No values are revealed or checked.</p><div class="table-scroll"><table><caption>Your trace of total</caption><thead><tr><th scope="col">Pass</th><th scope="col">value</th><th scope="col">total after pass</th></tr></thead><tbody>${[2,4,6].map((n,i)=>`<tr><th scope="row">${i+1}</th><td>${n}</td><td>${exampleField('trace'+i,`Total after pass ${i+1}`)}</td></tr>`).join('')}</tbody></table></div>`:`<button class="button" id="open-trace" ${!(exampleState.values.prediction||'').trim()?'disabled':''}>Keep prediction & open trace</button>`}</section></div>`;}
function orderExample(){return `<p class="lead">Arrange these blocks into a program that adds the values and prints the total. Keep the indented statement inside the loop.</p><ol class="code-order">${exampleState.order.map((line,i)=>`<li><span class="order-index">${i+1}</span><pre><code>${escapeText(line)}</code></pre><div class="move-controls"><button class="button secondary" data-move="${i},-1" aria-label="Move block ${i+1} up" ${i===0?'disabled':''}>↑</button><button class="button secondary" data-move="${i},1" aria-label="Move block ${i+1} down" ${i===exampleState.order.length-1?'disabled':''}>↓</button></div></li>`).join('')}</ol><p class="micro">Use the arrow buttons with a keyboard or touch. Block order is retained when you switch examples.</p>`;}
function tableExample(){return `<p class="lead">A cyclist travels at a steady 3 meters per second. Complete the distance column and explain the relationship.</p><div class="table-scroll"><table><caption>Distance over time</caption><thead><tr><th scope="col">Time (s)</th><th scope="col">Speed (m/s)</th><th scope="col">Your distance (m)</th></tr></thead><tbody>${[2,5,8].map(t=>`<tr><th scope="row">${t}</th><td>3</td><td>${exampleField('distance'+t,`Distance at ${t} seconds`)}</td></tr>`).join('')}</tbody></table></div>${exampleField('relationship','Explain your rule',true)}`;}
function visualExample(){return `<div class="task-split"><section><svg class="question-chart" viewBox="0 0 380 270" role="img" aria-label="Scatter plot: A at time 1 distance 2, B at time 2 distance 4, C at time 3 distance 3, D at time 4 distance 8."><g stroke="var(--line)"><path d="M45 35V225H345M45 185H345M45 145H345M45 105H345M45 65H345"/></g><text x="140" y="260">Time (seconds)</text><text x="45" y="20">Distance (meters)</text>${[['A',105,185],['B',165,145],['C',225,165],['D',285,65]].map(([name,x,y])=>`<circle cx="${x}" cy="${y}" r="9" fill="${exampleState.points.includes(name)?'var(--accent)':'var(--chart)'}" stroke="var(--ink)" stroke-width="${exampleState.points.includes(name)?4:1}"/><text x="${x+13}" y="${y+4}">${name}${exampleState.points.includes(name)?' ✓':''}</text>`).join('')}<text x="24" y="229">0</text><text x="24" y="189">2</text><text x="24" y="149">4</text><text x="24" y="109">6</text><text x="24" y="69">8</text>${[1,2,3,4].map((n,i)=>`<text x="${102+i*60}" y="243">${n}</text>`).join('')}</svg></section><fieldset><legend>Select every point where distance is twice time.</legend>${[['A','1 second, 2 meters'],['B','2 seconds, 4 meters'],['C','3 seconds, 3 meters'],['D','4 seconds, 8 meters']].map(([name,desc])=>`<label class="option"><input type="checkbox" data-point="${name}" ${exampleState.points.includes(name)?'checked':''}><span><strong>${name}</strong> · ${desc}</span></label>`).join('')}<p class="micro">The labeled controls provide the same task without precise pointing or color perception.</p></fieldset></div>`;}
function writtenExample(){return `<div class="task-split"><section><p class="eyebrow">EXAMINE THE ARGUMENT</p><dl class="argument"><dt>Premise 1</dt><dd>Every square has four equal sides.</dd><dt>Premise 2</dt><dd>This shape has four equal sides.</dd><dt>Conclusion</dt><dd>This shape must be a square.</dd></dl><p>Does the conclusion follow? Explain your reasoning and give an example that tests the claim.</p></section><section>${exampleField('argument','Your explanation',true)}${exampleField('counterexample','Your example or counterexample',true)}<details><summary>Review criteria</summary><p>A reviewer considers whether your reasoning addresses the implication and whether your example supports it. Written responses remain ungraded until review.</p></details></section></div>`;}
function examples(){const current=exampleKinds.find(x=>x[0]===exampleState.kind);const content={code:codeExample,order:orderExample,table:tableExample,visual:visualExample,written:writtenExample};return `<p class="eyebrow">QUESTION FORMATS / INTERACTIVE SHOWCASE</p><h1>Different thinking. Different tools.</h1><p class="lead">The question chooses the workspace. Code, diagrams, tables, and writing get the room and controls they need.</p><div class="format-picker" role="group" aria-label="Question format">${exampleKinds.map(([key,name,desc])=>`<button data-format="${key}" aria-pressed="${key===exampleState.kind}"><strong>${name}</strong><span>${desc}</span></button>`).join('')}</div><section class="card format-workspace"><div class="section-head" style="margin-top:0"><h2 id="format-title" tabindex="-1">${current[1]}</h2><span class="pill">SYNTHETIC · NOT GRADED</span></div>${content[exampleState.kind]()}<div class="action-row"><p class="micro" style="margin:0">Drafts stay in this tab while you explore. Reload clears them.</p><button class="button" id="preview-draft">Review my draft →</button></div>${exampleState.preview?`<section class="feedback" tabindex="-1" id="draft-review"><h2>Your response preview</h2><p>No correctness check was run. This shows the response a real activity would send to its runtime.</p><pre class="draft-preview">${escapeText(draftSummary())}</pre></section>`:''}<div id="format-status" role="status" class="micro"></div></section><p class="fixture-note">Production mapping: existing item contracts own response shape and disclosure. Editors, execution, tracing and review are separate capabilities. <a href="#references">See the design references →</a></p>`;}
function draftSummary(){const v=exampleState.values;switch(exampleState.kind){case 'code':return JSON.stringify({prediction:v.initialPrediction??v.prediction??'',trace:[0,1,2].map(i=>v['trace'+i]??''),repairDraft:v.repair??'(not edited)'},null,2);case 'order':return exampleState.order.join('\n');case 'table':return JSON.stringify({distances:[2,5,8].map(t=>({time:t,distance:v['distance'+t]??''})),explanation:v.relationship??''},null,2);case 'visual':return 'Selected points: '+(exampleState.points.join(', ')||'(none)');case 'written':return (v.argument||'(no explanation yet)')+'\n\nExample: '+(v.counterexample||'(none)');}}
function referencePage(){return `<p class="eyebrow">DESIGN NOTEBOOK / SOURCES</p><h1>What we’re learning from.</h1><p class="lead">A visible record of the references, useful patterns, and limits behind this showcase. Inspiration is not a claim of feature parity.</p><p class="micro">Research date: September 18, 2026. Earlier landscape entries retain their September 8 date.</p><div class="reference-grid">${designReferences.map(r=>`<article class="card"><div class="row"><h2><a href="${r.url}" target="_blank" rel="noopener noreferrer">${r.name} ↗</a></h2><span class="pill">${r.tag}</span></div><p><strong>Useful pattern:</strong> ${r.use}</p><p><strong>Here:</strong> ${r.here}</p><p class="micro"><strong>Evidence:</strong> ${r.evidence}</p></article>`).join('')}</div><section class="card" style="margin-top:24px"><h2>The wider landscape</h2><p>Earlier research also covered source tools, authoring, offline distribution, and review. These are historical research leads, not newly verified integrations.</p><details><summary>Show the earlier project directory</summary><ul class="reference-directory">${earlierReferences.map(r=>`<li><a href="${r.url}" target="_blank" rel="noopener noreferrer">${r.name} ↗</a></li>`).join('')}</ul></details><div class="action-row"><a class="text-link" href="REFERENCES.md">Readable reference index</a><a class="text-link" href="research/references.md">Full evidence and adoption notes</a></div></section>`;}
document.addEventListener('input',e=>{const key=e.target.dataset.response;if(key){exampleState.values[key]=e.target.value;exampleState.preview=false;document.querySelector('#draft-review')?.remove();if(key==='prediction'&&document.querySelector('#open-trace'))document.querySelector('#open-trace').disabled=!e.target.value.trim();}});
document.addEventListener('change',e=>{if(e.target.dataset.point){const p=e.target.dataset.point;exampleState.points=exampleState.points.filter(x=>x!==p);if(e.target.checked)exampleState.points.push(p);exampleState.preview=false;render();document.querySelector(`[data-point="${p}"]`).focus();}});
document.addEventListener('click',e=>{
 const format=e.target.closest('[data-format]');if(format){exampleState.kind=format.dataset.format;exampleState.preview=false;render();document.querySelector('#format-title').focus();}
 if(e.target.closest('#open-trace')){exampleState.values.initialPrediction=exampleState.values.prediction;exampleState.traced=true;render();document.querySelector('[data-response="trace0"]').focus();}
 const move=e.target.closest('[data-move]');if(move){const [i,delta]=move.dataset.move.split(',').map(Number);const next=i+delta;if(next<0||next>=exampleState.order.length)return;[exampleState.order[i],exampleState.order[next]]=[exampleState.order[next],exampleState.order[i]];exampleState.preview=false;render();const direction=next===0?1:next===exampleState.order.length-1?-1:delta;document.querySelector(`[data-move="${next},${direction}"]`).focus();document.querySelector('#format-status').textContent=`Block moved to position ${next+1}.`;}
 if(e.target.closest('#preview-draft')){exampleState.preview=true;render();document.querySelector('#draft-review').focus();}
});
